spring:
  datasource:
    url: jdbc:postgresql://158.247.253.227:5432/mydatabase
    username: 'psh950'
    password: '02070325'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: jpa_test01  # 기본 스키마 설정
        format_sql: true
        show_sql: true  # 쿼리 콘솔 로그 확인
        use_sql_comments: true  # jpql 로그 확인
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug