spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://158.247.253.227:5432/mydatabase
    username: 'psh950'
    password: '02070325'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: psh_db  # 테스트 db 스키마로 이동
        format_sql: true
        show_sql: true  # 쿼리 콘솔 로그 확인
        use_sql_comments: true  # jpql 로그 확인
logging:
  level:
    org:
      hibernate:
        SQL: debug