# PostgreSQL 16을 사용한 공식 이미지 기반
FROM postgres:16

# 환경 변수를 설정하여 PostgreSQL 초기 설정
ENV POSTGRES_USER=psh950
ENV POSTGRES_PASSWORD=02070325
ENV POSTGRES_DB=mydatabase

# 필요한 경우 추가 설정이나 초기화 스크립트를 추가
# COPY init.sql /docker-entrypoint-initdb.d/